### PR TITLE
Fix running tests on forks, and handle invalid URIs when fingerprinting

### LINKED ISSUE #1542: `Error: URI malformed` should report the input / offset
Fwiw, I've been using the same workflow for months now, so I don't see why it would suddenly change its behavior. That said, it doesn't really matter why it changed whether it's my code or the library's code. It would be very helpful to any user of this action if it were to report at least the URI it didn't like, and, if at all possible, the source of the URI.

https://github.com/check-spelling/sdk-ng/actions/runs/4200335289/jobs/7286246387

```
Download action repository 'github/codeql-action@v2' (SHA:17573ee1cc1b9d061760f3a006fc4aac4f944fd5)
```

Run [github/codeql-action/upload-sarif@v2](https://github.com/github/codeql-action/tree/17573ee1cc1b9d061760f3a006fc4aac4f944fd5)
> Uploading results
  Processing sarif files: `["/tmp/tmp.cTD1j4ui9R.sarif.json"]`
  `Error: URI malformed`
  `URIError: URI malformed`
> at `decodeURIComponent` (<anonymous>)
> at `resolveUriToFile` ([/home/runner/work/_actions/github/codeql-action/v2/lib/fingerprints.js:197](https://github.com/github/codeql-action/blob/17573ee1cc1b9d061760f3a006fc4aac4f944fd5/lib/fingerprints.js#L197):15)
> at `Object.addFingerprints` ([/home/runner/work/_actions/github/codeql-action/v2/lib/fingerprints.js:251](https://github.com/github/codeql-action/blob/17573ee1cc1b9d061760f3a006fc4aac4f944fd5/lib/fingerprints.js#L251):30)
> at `uploadFiles` ([/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:245](https://github.com/github/codeql-action/blob/17573ee1cc1b9d061760f3a006fc4aac4f944fd5/lib/upload-lib.js#L245):32)
> at `Object.uploadFromActions` ([/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:136](https://github.com/github/codeql-action/blob/17573ee1cc1b9d061760f3a006fc4aac4f944fd5/lib/upload-lib.js#L136):18)
      at **async** `run` ([/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:48](https://github.com/github/codeql-action/blob/17573ee1cc1b9d061760f3a006fc4aac4f944fd5/lib/upload-sarif-action.js#L48):30)
      at **async** `runWrapper` ([/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:70](https://github.com/github/codeql-action/blob/17573ee1cc1b9d061760f3a006fc4aac4f944fd5/lib/upload-sarif-action.js#L70):9)

<details><summary>possible uris?</summary>

`jq . tmp.cTD1j4ui9R.sarif.json|grep '"uri"'|perl -pe 's/,$//;s/^\s*"uri": //;s/"//g'|sort -u`:

```
.github/workflows/ci.yml
.github/workflows/release.yml
.gitmodules
README.md
cmake/Zephyr-sdkConfig.cmake
cmake/Zephyr-sdkConfigVersion.cmake
cmake/zephyr/Kconfig
cmake/zephyr/generic.cmake
cmake/zephyr/host-tools.cmake
cmake/zephyr/target.cmake
cmake/zephyr_sdk_export.cmake
configs/aarch64-zephyr-elf.config
configs/arc-zephyr-elf.config
configs/arm-zephyr-eabi.config
configs/mips-zephyr-elf.config
configs/nios2-zephyr-elf.config
configs/riscv64-zephyr-elf.config
configs/sparc-zephyr-elf.config
configs/x86_64-zephyr-elf.config
configs/xtensa-espressif_esp32_zephyr-elf.config
configs/xtensa-espressif_esp32s2_zephyr-elf.config
configs/xtensa-intel_apl_adsp_zephyr-elf.config
configs/xtensa-intel_s1000_zephyr-elf.config
configs/xtensa-nxp_imx8m_adsp_zephyr-elf.config
configs/xtensa-nxp_imx_adsp_zephyr-elf.config
meta-zephyr-sdk/README.md
meta-zephyr-sdk/conf/distro/include/zephyr-sdk.inc
meta-zephyr-sdk/conf/distro/zephyr-sdk.conf
meta-zephyr-sdk/conf/layer.conf
meta-zephyr-sdk/files/additional-licenses/DABAEZ
meta-zephyr-sdk/files/additional-licenses/SHUMATECH
meta-zephyr-sdk/recipes-core/expat/expat_%.bbappend
meta-zephyr-sdk/recipes-core/udev/eudev_%.bbappend
meta-zephyr-sdk/recipes-devtools/arc_qemu/arc-qemu_git.bb
meta-zephyr-sdk/recipes-devtools/arc_qemu/files/cross.patch
meta-zephyr-sdk/recipes-devtools/meson/meson.inc
meta-zephyr-sdk/recipes-devtools/meson/meson/0001-Make-CPU-family-warnings-fatal.patch
meta-zephyr-sdk/recipes-devtools/meson/meson/0001-gtkdoc-fix-issues-that-arise-when-cross-compiling.patch
meta-zephyr-sdk/recipes-devtools/meson/meson/0001-is_debianlike-always-return-False.patch
meta-zephyr-sdk/recipes-devtools/meson/meson/0001-python-module-do-not-manipulate-the-environment-when.patch
meta-zephyr-sdk/recipes-devtools/meson/meson/0002-Support-building-allarch-recipes-again.patch
meta-zephyr-sdk/recipes-devtools/meson/meson/disable-rpath-handling.patch
meta-zephyr-sdk/recipes-devtools/meson/meson/meson-setup.py
meta-zephyr-sdk/recipes-devtools/meson/meson/meson-wrapper
meta-zephyr-sdk/recipes-devtools/meson/meson_0.59.3.bb
meta-zephyr-sdk/recipes-devtools/meson/nativesdk-meson_0.59.3.bb
meta-zephyr-sdk/recipes-devtools/qemu/files/cross.patch
meta-zephyr-sdk/recipes-devtools/qemu/zephyr-qemu_git.bb
meta-zephyr-sdk/recipes-devtools/xilinx_qemu/files/0001-Revert-target-arm-Revert-back-to-YIELD-for-WFI.patch
meta-zephyr-sdk/recipes-devtools/xilinx_qemu/files/0002-Enable-WFI-CPU-halting-in-icount-mode.patch
meta-zephyr-sdk/recipes-devtools/xilinx_qemu/xilinx-qemu_git.bb
meta-zephyr-sdk/recipes-hosttools/bossa/bossa_git.bb
meta-zephyr-sdk/recipes-hosttools/bossa/files/0001-Flash.h-Add-flash-override-samba-error.patch
meta-zephyr-sdk/recipes-hosttools/bossa/files/0001-Wait-for-EEFC-flash-to-complete-operations-before-re.patch
meta-zephyr-sdk/recipes-hosttools/bossa/files/0002-CalwFlash-Add-SAM4L-Flashcalw-controller.patch
meta-zephyr-sdk/recipes-hosttools/bossa/files/0003-Device-Introduce-support-to-SAM4L-SoC-family.patch
meta-zephyr-sdk/recipes-hosttools/bossa/files/0004-CalwFlash-Add-NVIC-reset-command.patch
meta-zephyr-sdk/recipes-hosttools/hosttools/hosttools-tarball.bb
meta-zephyr-sdk/recipes-hosttools/openocd/openocd_git.bb
meta-zephyr-sdk/recipes-kernel/kmod/kmod_git.bbappend
meta-zephyr-sdk/recipes-support/hidapi/hidapi_git.bb
meta-zephyr-sdk/recipes-support/libftdi/libftdi_1.4.bb
meta-zephyr-sdk/recipes-support/libpcre/libpcre2_%.bbappend
meta-zephyr-sdk/recipes-support/libpcre/libpcre_%.bbappend
meta-zephyr-sdk/recipes-support/libusb/libusb-compat/0001-usb.h-Include-sys-types.h.patch
meta-zephyr-sdk/recipes-support/libusb/libusb-compat_0.1.7.bb
meta-zephyr-sdk/scripts/meta-zephyr-sdk-build.sh
meta-zephyr-sdk/scripts/meta-zephyr-sdk-clone.sh
meta-zephyr-sdk/scripts/template_dir
overlays/README.md
overlays/xtensa_espressif_esp32/binutils/bfd/xtensa-modules.c
overlays/xtensa_espressif_esp32/binutils/include/xtensa-config.h
overlays/xtensa_espressif_esp32/gcc/include/xtensa-config.h
overlays/xtensa_espressif_esp32/gdb/bfd/xtensa-modules.c
overlays/xtensa_espressif_esp32/gdb/gdb/regformats/reg-xtensa.dat
overlays/xtensa_espressif_esp32/gdb/gdb/xtensa-config.c
overlays/xtensa_espressif_esp32/gdb/gdb/xtensa-xtregs.c
overlays/xtensa_espressif_esp32/gdb/gdbserver/xtensa-xtregs.cc
overlays/xtensa_espressif_esp32/gdb/include/xtensa-config.h
overlays/xtensa_espressif_esp32/newlib/newlib/libc/sys/xtensa/include/xtensa/config/core-isa.h
overlays/xtensa_espressif_esp32s2/binutils/bfd/xtensa-modules.c
overlays/xtensa_espressif_esp32s2/gdb/bfd/xtensa-modules.c
overlays/xtensa_espressif_esp32s2/gdb/gdb/regformats/reg-xtensa.dat
overlays/xtensa_espressif_esp32s2/gdb/gdb/xtensa-config.c
overlays/xtensa_espressif_esp32s2/gdb/gdb/xtensa-xtregs.c
overlays/xtensa_espressif_esp32s2/gdb/gdbserver/xtensa-xtregs.cc
overlays/xtensa_espressif_esp32s2/gdb/include/xtensa-config.h
overlays/xtensa_espressif_esp32s2/newlib/newlib/libc/sys/xtensa/include/xtensa/config/core-isa.h
overlays/xtensa_intel_apl_adsp/binutils/bfd/xtensa-modules.c
overlays/xtensa_intel_apl_adsp/binutils/include/xtensa-config.h
overlays/xtensa_intel_apl_adsp/gcc/include/xtensa-config.h
overlays/xtensa_intel_apl_adsp/gdb/bfd/xtensa-modules.c
overlays/xtensa_intel_apl_adsp/gdb/gdb/regformats/reg-xtensa.dat
overlays/xtensa_intel_apl_adsp/gdb/gdb/xtensa-config.c
overlays/xtensa_intel_apl_adsp/gdb/gdb/xtensa-xtregs.c
overlays/xtensa_intel_apl_adsp/gdb/gdbserver/xtensa-xtregs.cc
overlays/xtensa_intel_apl_adsp/gdb/include/xtensa-config.h
overlays/xtensa_intel_apl_adsp/newlib/newlib/libc/sys/xtensa/include/xtensa/config/core-isa.h
overlays/xtensa_intel_s1000/binutils/bfd/xtensa-modules.c
overlays/xtensa_intel_s1000/binutils/include/xtensa-config.h
overlays/xtensa_intel_s1000/gdb/bfd/xtensa-modules.c
overlays/xtensa_intel_s1000/gdb/gdb/regformats/reg-xtensa.dat
overlays/xtensa_intel_s1000/gdb/gdb/xtensa-config.c
overlays/xtensa_intel_s1000/gdb/gdb/xtensa-xtregs.c
overlays/xtensa_intel_s1000/gdb/gdbserver/xtensa-xtregs.cc
overlays/xtensa_intel_s1000/newlib/newlib/libc/sys/xtensa/include/xtensa/config/core-isa.h
overlays/xtensa_nxp_imx8m_adsp/binutils/bfd/xtensa-modules.c
overlays/xtensa_nxp_imx8m_adsp/gdb/bfd/xtensa-modules.c
overlays/xtensa_nxp_imx8m_adsp/gdb/gdb/regformats/reg-xtensa.dat
overlays/xtensa_nxp_imx8m_adsp/gdb/gdb/xtensa-config.c
overlays/xtensa_nxp_imx8m_adsp/gdb/gdb/xtensa-xtregs.c
overlays/xtensa_nxp_imx8m_adsp/gdb/gdbserver/xtensa-xtregs.cc
overlays/xtensa_nxp_imx8m_adsp/newlib/newlib/libc/sys/xtensa/include/xtensa/config/core-isa.h
overlays/xtensa_nxp_imx_adsp/binutils/bfd/xtensa-modules.c
overlays/xtensa_nxp_imx_adsp/gdb/bfd/xtensa-modules.c
overlays/xtensa_nxp_imx_adsp/gdb/gdb/regformats/reg-xtensa.dat
overlays/xtensa_nxp_imx_adsp/gdb/gdb/xtensa-config.c
overlays/xtensa_nxp_imx_adsp/newlib/newlib/libc/sys/xtensa/include/xtensa/config/core-isa.h
overlays/xtensa_sample_controller/binutils/bfd/xtensa-modules.c
overlays/xtensa_sample_controller/gdb/bfd/xtensa-modules.c
overlays/xtensa_sample_controller/gdb/gdb/regformats/reg-xtensa.dat
overlays/xtensa_sample_controller/gdb/gdb/xtensa-config.c
overlays/xtensa_sample_controller/newlib/newlib/libc/sys/xtensa/include/xtensa/config/core-isa.h
release-notes.md
scripts/template_setup_posix
scripts/template_setup_win
```
</details>

### PR DESCRIPTION
**Pull request by jsoref**
* closes #1542 
* fixes tests on forks (organizations with restrictive permissions and repositories not named `github/codeql-action`)

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

### CODE REVIEW

File: src/workflow.ts [hunk 1]
```diff
@@ -389,7 +389,8 @@ function getInputOrThrow(
  * This allows us to test workflow parsing functionality as a CodeQL Action PR check.
  */
 function getAnalyzeActionName() {
-  if (getRequiredEnvParam("GITHUB_REPOSITORY") === "github/codeql-action") {
+  if (getRequiredEnvParam("GITHUB_REPOSITORY") === "github/codeql-action" ||
+      fs.existsSync("pr-checks/checks/test-local-codeql.yml")) {
```
Comment (henrymercer) [inline src/workflow.ts:393]: I'm not sure if we can rely on this since the first step of most of our PR checks moves the checkout into a different directory.  Could we instead check something like `util.isInTestMode() || process.env[CODEQL_ACTION_TESTING_ENVIRONMENT] == "codeql-action-pr-checks"`?  That should work for forks.

File: src/fingerprints.ts [hunk 2]
```diff
@@ -201,7 +201,14 @@ export function resolveUriToFile(
     logger.debug(`Ignoring location as URI "${location.uri}" is invalid`);
     return undefined;
   }
-  let uri = decodeURIComponent(location.uri as string);
+
+  let uri: string;
+  try {
+    uri = decodeURIComponent(location.uri as string);
+  } catch (e: any) {
+    logger.debug(`Ignoring location as URI "${location.uri}" is invalid`);
```
Comment (henrymercer) [inline src/fingerprints.ts:209]: Have you tried to upload a SARIF file to code scanning that fails the check here?  I'd expect that we might error out later on when we validate the schema or perhaps during processing on the server side.  Nevertheless, the error would make more sense there than here.

File: pr-checks/checks/analyze-ref-input.yml [hunk 3]
```diff
@@ -1,5 +1,8 @@
 name: "Analyze: 'ref' and 'sha' from inputs"
 description: "Checks that specifying 'ref' and 'sha' as inputs works"
+permissions:
+  contents: read
+  security-events: write
```
[the remark this answers is not in the document]
Comment (jsoref) [reply pr-checks/checks/analyze-ref-input.yml:5]: I did them iteratively and wasn't looking to see if the script could be adjusted.

I'm also annoyed that the comment about how to update doesn't say you need to be in the `pr-checks` directory. 

That said, yes, it seems editing the script would be reasonable.

File: src/init-action-post-helper.ts [hunk 4]
```diff
@@ -171,9 +171,15 @@ export async function run(
     process.env["CODEQL_ACTION_EXPECT_UPLOAD_FAILED_SARIF"] === "true" &&
     !uploadFailedSarifResult.raw_upload_size_bytes
   ) {
+    let error: string
+    if (uploadFailedSarifResult instanceof Error) {
```
[the remark this answers is not in the document]
Comment (jsoref) [reply src/init-action-post-helper.ts:175]: Yes, they're in https://github.com/check-spelling/github-codeql-action/actions

I don't think `stringify` likes error objects.

File: src/fingerprints.ts (hunk 2 above)
Comment (jsoref) [reply src/fingerprints.ts:209]: There's only one character that triggers this exception (`%`) and I regularly accidentally trip on this, it's why this PR exists, the rest is just to get tests to work.

I'm just trying to move the needle getting the debug output would be better than the current useless behavior.

File: src/init-action-post-helper.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (henrymercer) [reply src/init-action-post-helper.ts:175]: I couldn't find any cases where `uploadFailedSarifResult` is an `Error`, for example here (https://github.com/check-spelling/github-codeql-action/actions/runs/5052926623) it's an object.

I think we can rely on the type system here and unconditionally print `JSON.stringify(uploadFailedSarifResult)`.

File: src/workflow.ts (hunk 1 above)
Comment (henrymercer) [reply src/workflow.ts:393]: I think my suggestion should be a bit more robust.  I agree these hardcoded references aren't great since they can break running PR checks on forks.  Thanks for helping to remove them.

File: pr-checks/checks/analyze-ref-input.yml (hunk 3 above)
[the remark this answers is not in the document]
Comment (henrymercer) [reply pr-checks/checks/analyze-ref-input.yml:5]: > I'm also annoyed that the comment about how to update doesn't say you need to be in the `pr-checks` directory.

That's good feedback — feel free to update the generated file header in this PR, or I can update this separately.

File: src/fingerprints.ts (hunk 2 above)
Comment (jsoref) [reply src/fingerprints.ts:209]: I'm not sure `debug` is the ideal method call. Ideally it'd be something that the standard user sees, would that require something else like `error `?

**Comment by jsoref** [comment]
One final pain point: rate limits: https://github.com/check-spelling/github-codeql-action/actions/runs/5053027012 ... I'm not quite sure how to address this and thus I've left it out of scope, but it's problem.

File: src/fingerprints.ts (hunk 2 above)
Comment (henrymercer) [reply src/fingerprints.ts:209]: This is a little tricky since some tools (including CodeQL) produce their own fingerprint data, so it's not a problem if this logic fails.  So if we were upgrading this to `warning`, we'd probably want to make the log conditional on whether we had existing fingerprint data associated with that location.  I'd recommend leaving this as `debug` for now to keep things simple.  If the invalid URIs break the analysis, users will see a proper error message in the upload / processing stage of the Action.

**Review by henrymercer — COMMENTED** [review]
Thanks again for the contribution.  This LGTM once you've addressed the linter warnings.  If you could make sure `npm run build && npm test && npm run lint` succeeds locally before submitting we should be good to go.

Re rate limits, we have an item on the backlog to reduce the number of concurrent jobs that run with our PR checks.  We could also look at skipping certain PR checks when we run on forks, but that leaves a gap in test coverage I'm not entirely happy with.

**Comment by jsoref** [comment]
I'll try to do that this morning.

Note that:
* The read me file doesn't link to Contributing
* Contributing mentions node 14 which is almost certainly wrong

I really did look for a build file but didn't find one. I was trying to figure out if the project was `npm` or `yarn`.

File: src/init-action-post-helper.ts [hunk 5]
```diff
@@ -171,9 +171,10 @@
     process.env["CODEQL_ACTION_EXPECT_UPLOAD_FAILED_SARIF"] === "true" &&
     !uploadFailedSarifResult.raw_upload_size_bytes
   ) {
+    let error = JSON.stringify(uploadFailedSarifResult)
```
[the remark this answers is not in the document]
Comment (jsoref) [reply src/init-action-post-helper.ts:174]: The show more details link in:

Appears to link to:


And the other thing somehow managed to open my mobile browser without loading a specific web page, which is just surreal.

**Comment by jsoref** [comment]
Yes, disabling checks in forks is not what I'd want.

You could use a "variable" to specify a portion of the matrix to run for each test. That'd at least result in not starving forks of running capacity and allow users to change which set they're running between runs.

GitHub should allow running workflows to easily check on runner capacity and declaratively wait for capacity before starting a workflow. (This is very far beyond the scope of this PR, but I'm hoping you can send feedback to some internal team.)

It's probably possible to use workflow dispatch and have workflows chain from one to another. Sure it'd mean that things would be slower, but it's really painful to manually discover individual workflows that have failed and need to be rerun and then run then again. Again, this could be gated on a variable to allow the current behavior for people who have the capacity or tolerance.

**Review by henrymercer — APPROVED** [review]
Thanks for making the updates and your further suggestions around the contribution documentation and PR checks.  The `.github/workflows/pr-checks.yml` workflow does something similar to the chaining behaviour you suggest — I could see us doing something like that for other checks too.

**Comment by jsoref** [comment]
Fwiw, this change resulted in:
https://github.com/jsoref/examples-testing/actions/runs/5102140844/jobs/9171515485#step:2:1127

> Warning: 'this # file ( is 5) evil.txt' is not a valid URI in 'instance.runs[0].results[2].locations[0].physicalLocation.artifactLocation.uri'.

Which is a huge improvement.

I'd love for that to be surfaced, either by a problem-matcher or a `::warning`. If you're amenable to either, I can make a PR.

**Comment by aeisenberg** [comment]
Thanks for the suggestion, but I don't think that would be a good UX. There are some users of the `upload-sarif` action that rely on generating an invalid URL to signal that a certain file that is expected doesn't exist. See https://github.com/github/codeql-action/issues/1703. Using a problem matcher would mean that all users of this action will receive warnings when their workflow finds alerts.

There are things they could do differently to avoid using an invalid URL and we are going to work with them to fix it. But, until then I don't think there should be a warning here.
